/**
 * Test file to verify JWT token structure and role-based authentication
 * This can be used for debugging token-related issues
 */

// Example of token structure that should be generated by backend:
const exampleTokenPayload = {
    sub: "user@example.com",      // Subject (email)
    userId: 1,                     // User ID
    name: "User Name",             // User name
    role: "STUDENT",               // Role: STUDENT, INSTRUCTOR, or ADMIN
    iat: 1702742400,               // Issued at (timestamp)
    exp: 1702828800                // Expiration (timestamp)
}

// Role-based navigation mapping
const roleNavigationMap = {
    STUDENT: '/',
    INSTRUCTOR: '/instructor',
    ADMIN: '/admin'
}

// Protected routes configuration
const protectedRoutes = {
    '/my-learning': ['STUDENT', 'INSTRUCTOR', 'ADMIN'], // All authenticated users
    '/course/:id/learn': ['STUDENT', 'INSTRUCTOR', 'ADMIN'], // All authenticated users
    '/instructor': ['INSTRUCTOR'], // Only instructors
    '/admin': ['ADMIN'] // Only admins
}

console.log('JWT Token Structure:', exampleTokenPayload)
console.log('Role Navigation Map:', roleNavigationMap)
console.log('Protected Routes:', protectedRoutes)
